// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/atlas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Queue          string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	HandlerName    string                 `protobuf:"bytes,2,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Priority       int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,6,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Delay          *durationpb.Duration   `protobuf:"bytes,7,opt,name=delay,proto3" json:"delay,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_proto_atlas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *SubmitJobRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

func (x *SubmitJobRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubmitJobRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SubmitJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitJobRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *SubmitJobRequest) GetDelay() *durationpb.Duration {
	if x != nil {
		return x.Delay
	}
	return nil
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Inserted      bool                   `protobuf:"varint,3,opt,name=inserted,proto3" json:"inserted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_proto_atlas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitJobResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SubmitJobResponse) GetInserted() bool {
	if x != nil {
		return x.Inserted
	}
	return false
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_proto_atlas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State              string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	CurrentExecutionId string                 `protobuf:"bytes,3,opt,name=current_execution_id,json=currentExecutionId,proto3" json:"current_execution_id,omitempty"`
	RetryCount         int32                  `protobuf:"varint,4,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	LastError          string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	StateVersion       int32                  `protobuf:"varint,6,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	CancelRequested    bool                   `protobuf:"varint,7,opt,name=cancel_requested,json=cancelRequested,proto3" json:"cancel_requested,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_proto_atlas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{3}
}

func (x *JobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *JobStatusResponse) GetCurrentExecutionId() string {
	if x != nil {
		return x.CurrentExecutionId
	}
	return ""
}

func (x *JobStatusResponse) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *JobStatusResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *JobStatusResponse) GetStateVersion() int32 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *JobStatusResponse) GetCancelRequested() bool {
	if x != nil {
		return x.CancelRequested
	}
	return false
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_proto_atlas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{4}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Immediate     bool                   `protobuf:"varint,2,opt,name=immediate,proto3" json:"immediate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_proto_atlas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{5}
}

func (x *CancelJobResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CancelJobResponse) GetImmediate() bool {
	if x != nil {
		return x.Immediate
	}
	return false
}

type GetJobHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobHistoryRequest) Reset() {
	*x = GetJobHistoryRequest{}
	mi := &file_proto_atlas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobHistoryRequest) ProtoMessage() {}

func (x *GetJobHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetJobHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobHistoryRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ExecutionEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobHistoryResponse) Reset() {
	*x = JobHistoryResponse{}
	mi := &file_proto_atlas_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobHistoryResponse) ProtoMessage() {}

func (x *JobHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobHistoryResponse.ProtoReflect.Descriptor instead.
func (*JobHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{7}
}

func (x *JobHistoryResponse) GetEntries() []*ExecutionEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ExecutionEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId    string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	WorkerHostname string                 `protobuf:"bytes,2,opt,name=worker_hostname,json=workerHostname,proto3" json:"worker_hostname,omitempty"`
	Attempt        int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	StartedAt      string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt     string                 `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Outcome        string                 `protobuf:"bytes,6,opt,name=outcome,proto3" json:"outcome,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TraceId        string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionEntry) Reset() {
	*x = ExecutionEntry{}
	mi := &file_proto_atlas_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEntry) ProtoMessage() {}

func (x *ExecutionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEntry.ProtoReflect.Descriptor instead.
func (*ExecutionEntry) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{8}
}

func (x *ExecutionEntry) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionEntry) GetWorkerHostname() string {
	if x != nil {
		return x.WorkerHostname
	}
	return ""
}

func (x *ExecutionEntry) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ExecutionEntry) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ExecutionEntry) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *ExecutionEntry) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ExecutionEntry) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExecutionEntry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_atlas_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{9}
}

func (x *StreamRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State           string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	StateVersion    int32                  `protobuf:"varint,3,opt,name=state_version,json=stateVersion,proto3" json:"state_version,omitempty"`
	CancelRequested bool                   `protobuf:"varint,4,opt,name=cancel_requested,json=cancelRequested,proto3" json:"cancel_requested,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobEvent) Reset() {
	*x = JobEvent{}
	mi := &file_proto_atlas_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEvent) ProtoMessage() {}

func (x *JobEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEvent.ProtoReflect.Descriptor instead.
func (*JobEvent) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{10}
}

func (x *JobEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *JobEvent) GetStateVersion() int32 {
	if x != nil {
		return x.StateVersion
	}
	return 0
}

func (x *JobEvent) GetCancelRequested() bool {
	if x != nil {
		return x.CancelRequested
	}
	return false
}

type QueueHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueHealthRequest) Reset() {
	*x = QueueHealthRequest{}
	mi := &file_proto_atlas_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueHealthRequest) ProtoMessage() {}

func (x *QueueHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueHealthRequest.ProtoReflect.Descriptor instead.
func (*QueueHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{11}
}

func (x *QueueHealthRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type QueueHealthResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Queue            string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	ConcurrencyLimit int64                  `protobuf:"varint,2,opt,name=concurrency_limit,json=concurrencyLimit,proto3" json:"concurrency_limit,omitempty"`
	Inflight         int64                  `protobuf:"varint,3,opt,name=inflight,proto3" json:"inflight,omitempty"`
	P99LatencyMs     float64                `protobuf:"fixed64,4,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	ErrorRate        float64                `protobuf:"fixed64,5,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueueHealthResponse) Reset() {
	*x = QueueHealthResponse{}
	mi := &file_proto_atlas_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueHealthResponse) ProtoMessage() {}

func (x *QueueHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atlas_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueHealthResponse.ProtoReflect.Descriptor instead.
func (*QueueHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_atlas_proto_rawDescGZIP(), []int{12}
}

func (x *QueueHealthResponse) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *QueueHealthResponse) GetConcurrencyLimit() int64 {
	if x != nil {
		return x.ConcurrencyLimit
	}
	return 0
}

func (x *QueueHealthResponse) GetInflight() int64 {
	if x != nil {
		return x.Inflight
	}
	return 0
}

func (x *QueueHealthResponse) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *QueueHealthResponse) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

var File_proto_atlas_proto protoreflect.FileDescriptor

const file_proto_atlas_proto_rawDesc = "" +
	"\n" +
	"\x11proto/atlas.proto\x12\x05atlas\x1a\x1egoogle/protobuf/duration.proto\"\xfc\x01\n" +
	"\x10SubmitJobRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12!\n" +
	"\fhandler_name\x18\x02 \x01(\tR\vhandlerName\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vmax_retries\x18\x06 \x01(\x05R\n" +
	"maxRetries\x12/\n" +
	"\x05delay\x18\a \x01(\v2\x19.google.protobuf.DurationR\x05delay\"\\\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1a\n" +
	"\binserted\x18\x03 \x01(\bR\binserted\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x82\x02\n" +
	"\x11JobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x120\n" +
	"\x14current_execution_id\x18\x03 \x01(\tR\x12currentExecutionId\x12\x1f\n" +
	"\vretry_count\x18\x04 \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\x12#\n" +
	"\rstate_version\x18\x06 \x01(\x05R\fstateVersion\x12)\n" +
	"\x10cancel_requested\x18\a \x01(\bR\x0fcancelRequested\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"G\n" +
	"\x11CancelJobResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1c\n" +
	"\timmediate\x18\x02 \x01(\bR\timmediate\"-\n" +
	"\x14GetJobHistoryRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"E\n" +
	"\x12JobHistoryResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.atlas.ExecutionEntryR\aentries\"\x90\x02\n" +
	"\x0eExecutionEntry\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12'\n" +
	"\x0fworker_hostname\x18\x02 \x01(\tR\x0eworkerHostname\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x05 \x01(\tR\n" +
	"finishedAt\x12\x18\n" +
	"\aoutcome\x18\x06 \x01(\tR\aoutcome\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\"&\n" +
	"\rStreamRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x87\x01\n" +
	"\bJobEvent\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12#\n" +
	"\rstate_version\x18\x03 \x01(\x05R\fstateVersion\x12)\n" +
	"\x10cancel_requested\x18\x04 \x01(\bR\x0fcancelRequested\"*\n" +
	"\x12QueueHealthRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"\xb9\x01\n" +
	"\x13QueueHealthResponse\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12+\n" +
	"\x11concurrency_limit\x18\x02 \x01(\x03R\x10concurrencyLimit\x12\x1a\n" +
	"\binflight\x18\x03 \x01(\x03R\binflight\x12$\n" +
	"\x0ep99_latency_ms\x18\x04 \x01(\x01R\fp99LatencyMs\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x05 \x01(\x01R\terrorRate2\xa1\x03\n" +
	"\n" +
	"AtlasQueue\x12>\n" +
	"\tSubmitJob\x12\x17.atlas.SubmitJobRequest\x1a\x18.atlas.SubmitJobResponse\x12D\n" +
	"\fGetJobStatus\x12\x1a.atlas.GetJobStatusRequest\x1a\x18.atlas.JobStatusResponse\x12>\n" +
	"\tCancelJob\x12\x17.atlas.CancelJobRequest\x1a\x18.atlas.CancelJobResponse\x12G\n" +
	"\rGetJobHistory\x12\x1b.atlas.GetJobHistoryRequest\x1a\x19.atlas.JobHistoryResponse\x12;\n" +
	"\x10StreamJobUpdates\x12\x14.atlas.StreamRequest\x1a\x0f.atlas.JobEvent0\x01\x12G\n" +
	"\x0eGetQueueHealth\x12\x19.atlas.QueueHealthRequest\x1a\x1a.atlas.QueueHealthResponseB Z\x1egithub.com/yourorg/atlas/protob\x06proto3"

var (
	file_proto_atlas_proto_rawDescOnce sync.Once
	file_proto_atlas_proto_rawDescData []byte
)

func file_proto_atlas_proto_rawDescGZIP() []byte {
	file_proto_atlas_proto_rawDescOnce.Do(func() {
		file_proto_atlas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_atlas_proto_rawDesc), len(file_proto_atlas_proto_rawDesc)))
	})
	return file_proto_atlas_proto_rawDescData
}

var file_proto_atlas_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_atlas_proto_goTypes = []any{
	(*SubmitJobRequest)(nil),     // 0: atlas.SubmitJobRequest
	(*SubmitJobResponse)(nil),    // 1: atlas.SubmitJobResponse
	(*GetJobStatusRequest)(nil),  // 2: atlas.GetJobStatusRequest
	(*JobStatusResponse)(nil),    // 3: atlas.JobStatusResponse
	(*CancelJobRequest)(nil),     // 4: atlas.CancelJobRequest
	(*CancelJobResponse)(nil),    // 5: atlas.CancelJobResponse
	(*GetJobHistoryRequest)(nil), // 6: atlas.GetJobHistoryRequest
	(*JobHistoryResponse)(nil),   // 7: atlas.JobHistoryResponse
	(*ExecutionEntry)(nil),       // 8: atlas.ExecutionEntry
	(*StreamRequest)(nil),        // 9: atlas.StreamRequest
	(*JobEvent)(nil),             // 10: atlas.JobEvent
	(*QueueHealthRequest)(nil),   // 11: atlas.QueueHealthRequest
	(*QueueHealthResponse)(nil),  // 12: atlas.QueueHealthResponse
	(*durationpb.Duration)(nil),  // 13: google.protobuf.Duration
}
var file_proto_atlas_proto_depIdxs = []int32{
	13, // 0: atlas.SubmitJobRequest.delay:type_name -> google.protobuf.Duration
	8,  // 1: atlas.JobHistoryResponse.entries:type_name -> atlas.ExecutionEntry
	0,  // 2: atlas.AtlasQueue.SubmitJob:input_type -> atlas.SubmitJobRequest
	2,  // 3: atlas.AtlasQueue.GetJobStatus:input_type -> atlas.GetJobStatusRequest
	4,  // 4: atlas.AtlasQueue.CancelJob:input_type -> atlas.CancelJobRequest
	6,  // 5: atlas.AtlasQueue.GetJobHistory:input_type -> atlas.GetJobHistoryRequest
	9,  // 6: atlas.AtlasQueue.StreamJobUpdates:input_type -> atlas.StreamRequest
	11, // 7: atlas.AtlasQueue.GetQueueHealth:input_type -> atlas.QueueHealthRequest
	1,  // 8: atlas.AtlasQueue.SubmitJob:output_type -> atlas.SubmitJobResponse
	3,  // 9: atlas.AtlasQueue.GetJobStatus:output_type -> atlas.JobStatusResponse
	5,  // 10: atlas.AtlasQueue.CancelJob:output_type -> atlas.CancelJobResponse
	7,  // 11: atlas.AtlasQueue.GetJobHistory:output_type -> atlas.JobHistoryResponse
	10, // 12: atlas.AtlasQueue.StreamJobUpdates:output_type -> atlas.JobEvent
	12, // 13: atlas.AtlasQueue.GetQueueHealth:output_type -> atlas.QueueHealthResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_atlas_proto_init() }
func file_proto_atlas_proto_init() {
	if File_proto_atlas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_atlas_proto_rawDesc), len(file_proto_atlas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_atlas_proto_goTypes,
		DependencyIndexes: file_proto_atlas_proto_depIdxs,
		MessageInfos:      file_proto_atlas_proto_msgTypes,
	}.Build()
	File_proto_atlas_proto = out.File
	file_proto_atlas_proto_goTypes = nil
	file_proto_atlas_proto_depIdxs = nil
}
