// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/atlas.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AtlasQueue_SubmitJob_FullMethodName        = "/atlas.AtlasQueue/SubmitJob"
	AtlasQueue_GetJobStatus_FullMethodName     = "/atlas.AtlasQueue/GetJobStatus"
	AtlasQueue_CancelJob_FullMethodName        = "/atlas.AtlasQueue/CancelJob"
	AtlasQueue_GetJobHistory_FullMethodName    = "/atlas.AtlasQueue/GetJobHistory"
	AtlasQueue_StreamJobUpdates_FullMethodName = "/atlas.AtlasQueue/StreamJobUpdates"
	AtlasQueue_GetQueueHealth_FullMethodName   = "/atlas.AtlasQueue/GetQueueHealth"
)

// AtlasQueueClient is the client API for AtlasQueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AtlasQueueClient interface {
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error)
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error)
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
	GetJobHistory(ctx context.Context, in *GetJobHistoryRequest, opts ...grpc.CallOption) (*JobHistoryResponse, error)
	StreamJobUpdates(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
	GetQueueHealth(ctx context.Context, in *QueueHealthRequest, opts ...grpc.CallOption) (*QueueHealthResponse, error)
}

type atlasQueueClient struct {
	cc grpc.ClientConnInterface
}

func NewAtlasQueueClient(cc grpc.ClientConnInterface) AtlasQueueClient {
	return &atlasQueueClient{cc}
}

func (c *atlasQueueClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitJobResponse)
	err := c.cc.Invoke(ctx, AtlasQueue_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *atlasQueueClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatusResponse)
	err := c.cc.Invoke(ctx, AtlasQueue_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *atlasQueueClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, AtlasQueue_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *atlasQueueClient) GetJobHistory(ctx context.Context, in *GetJobHistoryRequest, opts ...grpc.CallOption) (*JobHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobHistoryResponse)
	err := c.cc.Invoke(ctx, AtlasQueue_GetJobHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *atlasQueueClient) StreamJobUpdates(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AtlasQueue_ServiceDesc.Streams[0], AtlasQueue_StreamJobUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AtlasQueue_StreamJobUpdatesClient = grpc.ServerStreamingClient[JobEvent]

func (c *atlasQueueClient) GetQueueHealth(ctx context.Context, in *QueueHealthRequest, opts ...grpc.CallOption) (*QueueHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueHealthResponse)
	err := c.cc.Invoke(ctx, AtlasQueue_GetQueueHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AtlasQueueServer is the server API for AtlasQueue service.
// All implementations must embed UnimplementedAtlasQueueServer
// for forward compatibility.
type AtlasQueueServer interface {
	SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
	GetJobStatus(context.Context, *GetJobStatusRequest) (*JobStatusResponse, error)
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	GetJobHistory(context.Context, *GetJobHistoryRequest) (*JobHistoryResponse, error)
	StreamJobUpdates(*StreamRequest, grpc.ServerStreamingServer[JobEvent]) error
	GetQueueHealth(context.Context, *QueueHealthRequest) (*QueueHealthResponse, error)
	mustEmbedUnimplementedAtlasQueueServer()
}

// UnimplementedAtlasQueueServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAtlasQueueServer struct{}

func (UnimplementedAtlasQueueServer) SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedAtlasQueueServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*JobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedAtlasQueueServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedAtlasQueueServer) GetJobHistory(context.Context, *GetJobHistoryRequest) (*JobHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobHistory not implemented")
}
func (UnimplementedAtlasQueueServer) StreamJobUpdates(*StreamRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamJobUpdates not implemented")
}
func (UnimplementedAtlasQueueServer) GetQueueHealth(context.Context, *QueueHealthRequest) (*QueueHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQueueHealth not implemented")
}
func (UnimplementedAtlasQueueServer) mustEmbedUnimplementedAtlasQueueServer() {}
func (UnimplementedAtlasQueueServer) testEmbeddedByValue()                    {}

// UnsafeAtlasQueueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AtlasQueueServer will
// result in compilation errors.
type UnsafeAtlasQueueServer interface {
	mustEmbedUnimplementedAtlasQueueServer()
}

func RegisterAtlasQueueServer(s grpc.ServiceRegistrar, srv AtlasQueueServer) {
	// If the following call panics, it indicates UnimplementedAtlasQueueServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AtlasQueue_ServiceDesc, srv)
}

func _AtlasQueue_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtlasQueueServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtlasQueue_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtlasQueueServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AtlasQueue_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtlasQueueServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtlasQueue_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtlasQueueServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AtlasQueue_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtlasQueueServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtlasQueue_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtlasQueueServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AtlasQueue_GetJobHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtlasQueueServer).GetJobHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtlasQueue_GetJobHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtlasQueueServer).GetJobHistory(ctx, req.(*GetJobHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AtlasQueue_StreamJobUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AtlasQueueServer).StreamJobUpdates(m, &grpc.GenericServerStream[StreamRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AtlasQueue_StreamJobUpdatesServer = grpc.ServerStreamingServer[JobEvent]

func _AtlasQueue_GetQueueHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtlasQueueServer).GetQueueHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtlasQueue_GetQueueHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtlasQueueServer).GetQueueHealth(ctx, req.(*QueueHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AtlasQueue_ServiceDesc is the grpc.ServiceDesc for AtlasQueue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AtlasQueue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atlas.AtlasQueue",
	HandlerType: (*AtlasQueueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _AtlasQueue_SubmitJob_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _AtlasQueue_GetJobStatus_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _AtlasQueue_CancelJob_Handler,
		},
		{
			MethodName: "GetJobHistory",
			Handler:    _AtlasQueue_GetJobHistory_Handler,
		},
		{
			MethodName: "GetQueueHealth",
			Handler:    _AtlasQueue_GetQueueHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobUpdates",
			Handler:       _AtlasQueue_StreamJobUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/atlas.proto",
}
